server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  #模板引擎配置
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
  #配置静态资源
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

