name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install OpenCV manually
      run: |
       mvn install:install-file \
          -Dfile=src/main/resources/lib/opencv-452.jar \
          -DgroupId=org.opencv \
          -DartifactId=opencv \
          -Dversion=4.5.2 \
          -Dpackaging=jar

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean install

    # Upload the generated artifact (JAR file)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BlindWatermark-build
        path: target/*.jar
